In [1]:
import pandas as pd

### References:

Prolog Facts, Rules, Queries http://www.cs.trincoll.edu/~ram/cpsc352/notes/prolog/factsrules.html

chapter 16 "Pattern-directed systems" from book "PROLOG PROGRAMMING FOR ARTIFICIAL INTELLIGE" https://silp.iiita.ac.in/wp-content/uploads/PROLOG.pdf

In [2]:
df = pd.read_csv('second.csv')

In [3]:
df

,a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,class
0,True,False,False,False,True,False,True,True,True,True,False,False,False,True,c0
1,False,False,False,True,True,False,True,True,False,False,True,True,False,True,c1
2,False,True,True,False,False,False,False,False,True,False,True,True,False,True,c2
3,True,False,False,False,True,True,False,False,True,True,True,True,True,False,c3
4,True,True,False,True,False,True,False,True,True,True,True,True,False,True,c0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80,False,True,False,True,False,True,False,True,True,True,False,False,True,False,c0
81,True,True,True,False,False,True,False,False,True,False,True,False,False,False,c0
82,True,True,False,True,True,True,True,True,True,False,True,True,False,True,c3
83,True,False,True,True,True,True,False,False,True,False,True,False,False,True,c0
84,True,False,False,True,False,True,False,False,False,False,False,False,False,True,c0

In [7]:
df.columns

Index(['a0', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10',
       'a11', 'a12', 'a13', 'class'],
      dtype='object')

In [10]:
dfg = df.groupby(['class'])

In [50]:
dfg.get_group('c1')

,a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,class
1,False,False,False,True,True,False,True,True,False,False,True,True,False,True,c1
6,True,False,False,True,True,False,True,False,True,False,True,True,True,True,c1
8,True,False,True,True,True,False,True,False,False,False,True,True,False,True,c1
15,False,False,True,True,False,False,False,True,False,True,True,False,False,True,c1
16,False,True,False,True,True,True,False,True,True,False,True,False,True,True,c1
18,True,False,True,True,True,False,False,False,False,True,True,False,True,False,c1
20,False,True,True,True,True,False,False,False,False,True,False,True,True,False,c1
21,False,True,False,True,False,True,False,False,True,False,True,False,True,True,c1
25,False,False,True,True,True,False,False,False,False,False,False,True,False,False,c1
26,False,True,True,True,False,True,True,False,False,False,True,True,True,False,c1
27,False,True,False,True,False,True,False,True,False,True,True,True,False,False,c1
32,True,True,True,True,False,True,False,False,True,False,True,False,True,False,c1
34,False,False,True,True,True,False,False,False,False,True,True,True,False,False,c1
35,False,False,False,True,False,True,False,False,False,False,False,False,True,False,c1
37,True,True,False,True,True,False,True,True,False,False,True,False,False,True,c1
43,True,False,True,True,True,False,False,True,True,False,True,True,False,False,c1
44,False,False,False,True,True,True,False,True,True,True,True,False,True,False,c1
54,False,False,True,True,False,False,True,False,False,False,False,False,True,False,c1
61,False,True,False,True,True,False,False,True,False,True,True,False,False,True,c1
69,False,True,False,True,False,True,True,True,False,True,True,False,False,False,c1
72,False,False,False,True,True,False,False,True,False,True,True,False,True,True,c1
79,False,False,False,True,False,True,False,False,True,False,True,False,True,True,c1

a3 = false
| a10 = false: c0 (11.0/1.0)
| a10 = true
| | a2 = false
| | | a13 = false: c3 (12.0)
| | | a13 = true
| | | | a0 = false: c0 (2.0)
| | | | a0 = true: c3 (2.0)
| | a2 = true: c0 (7.0/2.0)
a3 = true
| a0 = false
| | a8 = false: c1 (12.0)
| | a8 = true
| | | a10 = false: c0 (5.0)
| | | a10 = true: c1 (4.0)
| a0 = true
| | a10 = false
| | | a8 = false
| | | | a4 = false: c2 (6.0/1.0)
| | | | a4 = true: c3 (2.0)
| | | a8 = true: c0 (7.0)
| | a10 = true
| | | a5 = false: c1 (5.0)
| | | a5 = true
| | | | a6 = false: c0 (7.0/2.0)
| | | | a6 = true: c3 (3.0)

Prolog Rules: (hand written) 

is_accuator_activated(a3, false), 
is_accuator_activated(a10, false) :- move(rover, forward).

is_accuator_activated(a3, false), 
is_accuator_activated(a10, true), 
is_accuator_activated(a2, true) :- move(rover, forward).

is_accuator_activated(a3, false), 
is_accuator_activated(a10, true), 
is_accuator_activated(a2, false), 
is_accuator_activated(a13, false) :- move(rover, backward).

is_accuator_activated(a3, false), 
is_accuator_activated(a10, true), 
is_accuator_activated(a2, false), 
is_accuator_activated(a13, true), 
is_accuator_activated(a0, false) :- move(rover, forward).

is_accuator_activated(a3, false), 
is_accuator_activated(a10, true), 
is_accuator_activated(a2, false), 
is_accuator_activated(a13, true), 
is_accuator_activated(a0, true) :- move(rover, backward).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, false), 
is_accuator_activated(a8, false) :- move(rover, left).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, false), 
is_accuator_activated(a8, true),
is_accuator_activated(a10, false) :- move(rover, forward).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, false), 
is_accuator_activated(a8, true),
is_accuator_activated(a10, true) :- move(rover, left).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, true), 
is_accuator_activated(a10, false), 
is_accuator_activated(a8, false), 
is_accuator_activated(a4, false):- move(rover, right).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, true), 
is_accuator_activated(a10, false), 
is_accuator_activated(a8, false), 
is_accuator_activated(a4, true):- move(rover, backward).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, true), 
is_accuator_activated(a10, false), 
is_accuator_activated(a8, true) :- move(rover, forward).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, true), 
is_accuator_activated(a10, true), 
is_accuator_activated(a5, false) :- move(rover, left).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, true), 
is_accuator_activated(a10, true), 
is_accuator_activated(a5, true), 
is_accuator_activated(a6, false):- move(rover, forward).

is_accuator_activated(a3, true), 
is_accuator_activated(a0, true), 
is_accuator_activated(a10, true), 
is_accuator_activated(a5, true), 
is_accuator_activated(a6, true) :- move(rover, backward).

In [61]:
decision_tree_for_prolog = '''a3 = false
| a10 = false: c0 (11.0/1.0)
| a10 = true
| | a2 = false
| | | a13 = false: c3 (12.0)
| | | a13 = true
| | | | a0 = false: c0 (2.0)
| | | | a0 = true: c3 (2.0)
| | a2 = true: c0 (7.0/2.0)
a3 = true
| a0 = false
| | a8 = false: c1 (12.0)
| | a8 = true
| | | a10 = false: c0 (5.0)
| | | a10 = true: c1 (4.0)
| a0 = true
| | a10 = false
| | | a8 = false
| | | | a4 = false: c2 (6.0/1.0)
| | | | a4 = true: c3 (2.0)
| | | a8 = true: c0 (7.0)
| | a10 = true
| | | a5 = false: c1 (5.0)
| | | a5 = true
| | | | a6 = false: c0 (7.0/2.0)
| | | | a6 = true: c3 (3.0)'''

import re
prolog_rules = []

pipe_map = {}

for line in decision_tree_for_prolog.split('\n'):
    line = line.replace(' ','')
    pipe_cnt = line.count('|')
    if pipe_cnt == 0:
        pipe_map[pipe_cnt] = line.replace('t','T').replace('f','F').replace('=','==')
    
    if '|' in line and ':' not in line:
        pipe_map[pipe_cnt] = re.findall(r"\|(.*)",line)[0].replace('|','').replace('t','T').replace('f','F').replace('=','==')
        
    if ':' in line:
        pipe_map[pipe_cnt] = re.findall(r"\|(.*?)\:",line)[0].replace('|','').replace('t','T').replace('f','F').replace('=','==')
        rule = ' and '.join([pipe_map[i].replace('a','a[').replace('==',']==').replace('Fa[','Fa') for i in range(pipe_cnt+1)])
        action = re.findall(r"\:(.*?)\(",line)[0]
        rule = ' '.join(rule.split())
        prolog_rules.append((rule,action))
            
    #  \|(.*)
    #  \|(.*?)\:
    #  \:(.*?)\(
    
from pprint import pprint
pprint(prolog_rules)

[('a[3]==False and a[10]==False', 'c0'),
 ('a[3]==False and a[10]==True and a[2]==False and a[13]==False', 'c3'),
 ('a[3]==False and a[10]==True and a[2]==False and a[13]==True and a[0]==False',
  'c0'),
 ('a[3]==False and a[10]==True and a[2]==False and a[13]==True and a[0]==True',
  'c3'),
 ('a[3]==False and a[10]==True and a[2]==True', 'c0'),
 ('a[3]==True and a[0]==False and a[8]==False', 'c1'),
 ('a[3]==True and a[0]==False and a[8]==True and a[10]==False', 'c0'),
 ('a[3]==True and a[0]==False and a[8]==True and a[10]==True', 'c1'),
 ('a[3]==True and a[0]==True and a[10]==False and a[8]==False and a[4]==False',
  'c2'),
 ('a[3]==True and a[0]==True and a[10]==False and a[8]==False and a[4]==True',
  'c3'),
 ('a[3]==True and a[0]==True and a[10]==False and a[8]==True', 'c0'),
 ('a[3]==True and a[0]==True and a[10]==True and a[5]==False', 'c1'),
 ('a[3]==True and a[0]==True and a[10]==True and a[5]==True and a[6]==False',
  'c0'),
 ('a[3]==True and a[0]==True and a[10]==True and a[5]==True and a[6]==True',
  'c3')]

In [73]:
process_parameters('TTTFTFTFFFTFTF')

'c0'

In [71]:
process_parameters('TFTTTFTFFFTFTF')

'c1'

In [86]:
n_matches = 0
for i in range(df.shape[0]):
    gen = process_parameters(''.join(['T' if p == True else 'F' for p in df.iloc[i].values if p in (True,False)]))
    #print('generated:',)
    act = df.iloc[i]['class']
    #print('actual   :',act)
    #print('-'*10)
    if gen == act: n_matches += 1
        
n_matches/df.shape[0]

0.9294117647058824

In [90]:
directions = {'c0':'Forword','c1':'Left','c2':'Right','c3':'Backward'}
user_wants_to_stop = False
while not user_wants_to_stop:
    input_params = input('enter 14 parameters to move rover(like TTTFTFTFFFTFTF) or enter "STOP" to exit:')
    if input_params == 'STOP' : break
    output = process_parameters(input_params)
    try:print('rover would move',output, 'i.e',directions[output])
    except:pass

enter 14 parameters to move rover(like TTTFTFTFFFTFTF) or enter "STOP" to exit:TTTFTFTFFFTFTQ
please enter only in format of 'T' and 'F'
enter 14 parameters to move rover(like TTTFTFTFFFTFTF) or enter "STOP" to exit:TTTFTFTFFFTFT
please input exactly 14 input parameters
enter 14 parameters to move rover(like TTTFTFTFFFTFTF) or enter "STOP" to exit:TTTFTFTFFFTFTF
rover would move c0 i.e Forword

KeyboardInterrupt: Interrupted by user

In [ ]:
a0 a1 a2 a3... a10 .. a13
T  F  F  F ... F   .. T   c0  
T  F  T  F ... F   .. F   c0
T  T  F  F ... F   .. T   c0
F  F  F  F ... F   .. F   c0
T  F  F  F ... F   .. T   c0

In [88]:
def process_parameters(input_params):
    params = list(input_params)
    if len(params) != 14:
        print("please input exactly 14 input parameters")
        return ''

    if set(list(input_params)) != set(('T','F')):
        print("please enter only in format of 'T' and 'F'")
        return ''
    
    a = [True if p == 'T' else False for p in input_params] 
    
    for rule,action in prolog_rules:
        if eval(rule):
            return action

In [69]:
{'F', 'T'} == {'F', 'T'}

True

In [62]:
[True if p == 'T' else False for p in 'TFTTTFTFFF']

[True, False, True, True, True, False, True, False, False, False]

In [ ]:
enter 14 parameters to move rover(like TFTTTFTFFF):

In [54]:
a = [False,False,False,False]
eval('a[3]==False')

True